### ISSUE TITLE
Tests fail if user running the tests doesn't have ~/.gitconfig

### ISSUE THREAD

**Issue by rikur** [libgit2/rugged#432]
Finished tests in 21.399766s, 21.2619 tests/s, 77.6644 assertions/s.

  1) Failure:
test_read_global_config_file(ConfigTest) [/home/riku.r/rugged/test/config_test.rb:19]:
Failed assertion, no message given.

455 tests, 1662 assertions, 1 failures, 0 errors, 0 skips

Tests will pass after running:
git config --global user.name 'Foo Bar'

**Comment by dvzrv** [comment]
I'm encountering the exact same issue during build and test of ruby-rugged for Arch Linux.

It's sort of interesting this bug never got fixed.

**Comment by kbrock** [comment]
I'm running into issues when running this as part of a daemon process that does not have access to the HOME directory

**Comment by carlosmn** [comment]
It's a bit of an edge condition since most places will just have it. I started trying to isolate the tests yesterday but spent most of the evening just trying to figure out how to get minitest to do what I wanted.

@kbrock if you're running a daemon then it's a different issue and you should specify a different search path for the config levels if you cannot use the defaults.

**Comment by carlosmn** [comment]
Fixed via #883
