### ISSUE TITLE
why the size equal 0 all diff_delta's new_file and old_file 

### ISSUE THREAD

**Issue by zouqilin** [libgit2/rugged#449]
diff.each_delta{|d| puts d.old_file; puts d.new_file}
{:oid=>"d2a4c7f61fa9bf15263d81d6d91ff6f53d4adc91", :path=>"sw/qa/extras/ooxmlexport/ooxmlfieldexport.cxx", :size=>0, :flags=>4, :mode=>33188}
{:oid=>"923a82ffc9695ccec56c4a5262b9e8b40931d871", :path=>"sw/qa/extras/ooxmlexport/ooxmlfieldexport.cxx", :size=>0, :flags=>4, :mode=>33188}
{:oid=>"48ebe66b5eccd1488680cdfda41845106c709bc8", :path=>"sw/source/filter/ww8/docxexport.cxx", :size=>0, :flags=>4, :mode=>33188}
{:oid=>"6cb7d80adebd4d193eda3d808f70cfb718e4a563", :path=>"sw/source/filter/ww8/docxexport.cxx", :size=>0, :flags=>4, :mode=>33188}

**Comment by zouqilin** [comment]
urge....

**Comment by arrbee** [comment]
If `diff` is a tree diff, the Git tree data does not include the sizes of the blobs, so for the sake of efficiency, libgit2 tries not to unpack the blobs unless necessary. In these cases, the OID has changed between the two tree revisions, so the we could tell for certain that the blobs were modified without expanding the blob data. Unfortunately, this means we don't know the blob size.

If you generate the patches for diffs, we have to expand the blob data and libgit2 will fill in the size field.

I don't think there is a libgit2 diff option to force the `size` field to be filled in for the cases where it is not necessary to determine the type of delta.

**Comment by zouqilin** [comment]
thk, i think i got it

**Comment by arthurschreiber** [comment]
@zouqilin Can this issue be closed?

@arrbee Would it make sense to document this somewhere?

**Comment by arrbee** [comment]
> @arrbee Would it make sense to document this somewhere?

Yes. The issue is mentioned in passing now as part of the documentation for `git_diff_delta` where we write "Under some circumstances, in the name of efficiency, not all fields will be filled in, but we generally try to fill in as much as possible." We go on to give an example of not classifying whether a file is binary or not in cases where we can avoid examining file contents.

We could expand the explanation there or add some related explanation to the `git_diff_file` struct. Alternatively, we could add a new `GIT_DIFF_...` option value to force deltas to look up the blob size for all diff entries and then document the default behavior as part of that flag that overrides the default. None of these solutions are ideal...

**Comment by molisoft** [comment]
HOHO
