### ISSUE TITLE
Cannot load libhttp_parser2.6.0

### ISSUE THREAD

**Issue by ss1h2a3tw** [libgit2/rugged#578]
I'm using Archlinux with the libhttp_parser2.6.1, while rugged.so inside gem pulls libhttp_parser.so.2.6.0
Here is the output of `ldd rugged.so`

>         linux-vdso.so.1 (0x00007fffcf172000)
        libcurl.so.4 => /usr/lib/libcurl.so.4 (0x00007f97def13000)
        libhttp_parser.so.2.6.0 => not found
        libssh2.so.1 => /usr/lib/libssh2.so.1 (0x00007f97dece7000)
        librt.so.1 => /usr/lib/librt.so.1 (0x00007f97deade000)
        libssl.so.1.0.0 => /usr/lib/libssl.so.1.0.0 (0x00007f97de863000)
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f97de64d000)
        libcrypto.so.1.0.0 => /usr/lib/libcrypto.so.1.0.0 (0x00007f97de1d4000)
        libruby.so.2.3 => /usr/lib/libruby.so.2.3 (0x00007f97ddd47000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f97ddb2a000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f97dd785000)
        libidn.so.11 => /usr/lib/libidn.so.11 (0x00007f97dd551000)
        libgssapi_krb5.so.2 => /usr/lib/libgssapi_krb5.so.2 (0x00007f97dd304000)
        libkrb5.so.3 => /usr/lib/libkrb5.so.3 (0x00007f97dd01e000)
        libk5crypto.so.3 => /usr/lib/libk5crypto.so.3 (0x00007f97dcded000)
        libcom_err.so.2 => /usr/lib/libcom_err.so.2 (0x00007f97dcbe9000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f97dc9e4000)
        libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007f97dc76c000)
        libcrypt.so.1 => /usr/lib/libcrypt.so.1 (0x00007f97dc534000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f97dc235000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00005574d6acd000)
        libkrb5support.so.0 => /usr/lib/libkrb5support.so.0 (0x00007f97dc028000)
        libkeyutils.so.1 => /usr/lib/libkeyutils.so.1 (0x00007f97dbe24000)
        libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f97dbc0c000)

**Comment by carlosmn** [comment]
Where did you get rugged from? Is it packaged by the distro? Did you build it yourself? Did you build it on this computer? Have you updated the http-parser package?

It looks like the `.pc` file provided by your version of http-parser (which IIRC has to be provided by your distribution) or the  is too specific and makes you link against the SONAME with a full version number instead of an api number.

If you have built this locally and have updated the http-parser package, you'll need to rebuild rugged, since your distribution removed the library you were linking to.

**Comment by ss1h2a3tw** [comment]
Oh, It's my fault. I'm running `gem install` instead of `bundle install`.
Sorry for bothering.
