### ISSUE TITLE
 v0.25.0 release

### ISSUE THREAD

**Issue by glensc** [libgit2/rugged#607]
hi

please consider doing stable release, so i could use gitlab properly:
https://gitlab.com/gitlab-org/gitlab-ce/issues/14972#note_12067782

**Comment by ethomson** [comment]
Hi!  Thanks for reaching out.  It's not clear to me that _any 0.25_ will help you, it seems like you want _a particular 0.25_...

1. It's not clear to me what the problem here was.  Do you have reproduction steps?  I'm glad that it suddenly works, but I would much rather have regression tests so that we could catch this problem if it were to happen again.

2. It looks like you're seeing a bug in GitLab...  and while the root cause may live in Rugged or libgit2, this seems like an issue that should be tracked _by GitLab_.  It's not clear what Rugged's next release will look like, if this bug will actually be fixed in it or not, if it will regress between now and then...  etc.

    A bug report or request that says "please do `<x>` because it will fix a problem in `<y>` is not actionable for us, because we don't control `<y>` and we don't know whether it will _actually_ help.  If you can provide a bug report that is "diffing `<this tree>` and `<that tree>` produce incorrect results" then this is actionable for us and something that we can respond to.  (And then we can talk about a timeline for fixing it.)

    Certainly I understand if that's not something that you're able to do - we understand that repositories often contain private data.
3. Otherwise, if you have particular requests for what the next release should look like, that would _also_ be an actionable request.  For example:  "I'm seeing a bug in diff based on this input, it was fixed in libgit2 commit `<x>`."  Then we'd also be able to talk about release dates.

    I say this because the libgit2 master branch, for example, is not necessarily stable or something that we're ready to release.  Various users of libgit2 do _a lot_ of testing in production with various fixes.  I think we're _just now_ nearly at the point where the next release of libgit2 would include the rewrite of the iterators that likely fixed the bug you're seeing.  But this is only recently true, had you asked me for an 0.25 two days ago, and had we agreed, we would have cut one _without that_ because we weren't done testing it.

Anyway.  I mention these things because I wanted to point out why asking us to fix a problem you're seeing in somebody else's project is something that's hard for us to do.  😄

**Comment by glensc** [comment]
yes, i can not provide reliable test data because it happens with private repo and without knowing what's the issue, i'm not able to reproduce the problem with generated repository.

as for particular problem i was having, i was able to narrow down the problem to libgit2:
- gitlab_git
- rugged
- libgit2

and the problem was solely reproduceable with the sample/diff program from libgit2. and having looked your latest 0.25.0b3 tag pointed to the libgit2 commit that had the problem solved, i assumed that is the libgit2 version that would be bundled with next rugged release.

and yes, i had plans for bisecting to the actual commit that fixed the problem, i planned to do that in next few days.

but my particular problem will be solved with rugged 0.25.0+ release, i'm like 99.99% sure of that, and gitlab guys said they would pin to newer release if such stable release happens, this is why i created this ticket here.

**Comment by glensc** [comment]
as the problem is solved somewhere in 
https://github.com/libgit2/libgit2/compare/v0.24.0...c75644

i created ticket there:
https://github.com/libgit2/libgit2/issues/3802

**Comment by carlosmn** [comment]
The tip of libgit2 master has a few bugs we only discovered after testing
it against production data. Even if we wanted to release 0.25 now we
wouldn't be able to.

This is why the maintenance branch and releases are made. So we can
backport applications without the rest of the changes that are more
experimental.
On May 26, 2016 7:31 PM, "Elan Ruusamäe" <notifications@github.com> wrote:

as the problem is solved somewhere in
libgit2/libgit2@v0.24.0...c75644
<https://github.com/libgit2/libgit2/compare/v0.24.0...c75644>

i created ticket there:
libgit2/libgit2#3802 <https://github.com/libgit2/libgit2/issues/3802>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/libgit2/rugged/issues/607#issuecomment-221939496>

**Comment by glensc** [comment]
@carlosmn has anything good changed since May?

**Comment by glensc** [comment]
0.25.0 along with 0.25.1 and 0.25.1.1 released, closing
