### ISSUE TITLE
Push error hash structure

### ISSUE THREAD

**Issue by jabbowaki** [libgit2/rugged#659]
The docs for [#push](http://www.rubydoc.info/github/libgit2/rugged/Rugged%2FRepository%3Apush) seem to suggest that any errors are returned in a hash instead of thrown as exceptions. What does the structure of the hash look like?

**Comment by spraints** [comment]
Its keys are refs, and the values are messages. So, something like `{"refs/heads/master" => "pre-receive hook declined"}`. If there are no errors, the Hash should be empty.

**Comment by fschwahn** [comment]
I've just run into an issue were a job silently failed because the push failed. My expectation would have been for `Rugged::Repository#push` to raise an error if the push fails. That expectation was so strong that I never even bothered checking. That's clearly my fault, but maybe the usability can be improved by having this raise an error?

**Comment by carlosmn** [comment]
It would not aid usability. Push reports errors as exceptions, but there is no way to have exceptions report partial failures. A push containing multiple ref updates can have one rejected and two succeed. The only sensible way to report what can happen in a push is to return a report about what the server said.
