### ISSUE TITLE
0.26.0 failing on Rubinius

### ISSUE THREAD

**Issue by eugenk** [libgit2/rugged#710]
On MRI:
```
irb(main):001:0> RUBY_DESCRIPTION
=> "ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]"
irb(main):002:0> require 'rugged'
=> true
irb(main):003:0> Rugged::Diff.new.methods.include?(:each_patch)
=> true
```

On Rubinius:
```
irb(main):001:0> RUBY_DESCRIPTION
=> "rubinius 3.82 (2.3.1 1a98abf9 2017-06-27 4.0.1) [x86_64-darwin16.6.0]"
irb(main):002:0> require 'rugged'
LoadError::InvalidExtensionError: Could not open library /Users/eugen/.gem/rbx/2.3.1/extensions/x86_64-darwin-16/2.3/rugged-0.26.0/rugged/rugged.bundle - dlopen(/Users/eugen/.gem/rbx/2.3.1/extensions/x86_64-darwin-16/2.3/rugged-0.26.0/rugged/rugged.bundle, 10): Symbol not found: _rb_hash_fetch
```

I found this problem in our test suite where, surprisingly, rugged could be loaded but it fails with:
```
NameError:
  undefined method `each_patch' for class `Rugged::Diff'
# core/zed.rb:60:in `alias_method'
```

This worked just fine on 0.25.1.

By the way, you test against an old version `rbx-2` of Rubinius in travis. The current version is `rbx-3.82`.

**Comment by tenderlove** [comment]
I think this is a bug in Rubinius.  MRI exports a `rb_hash_fetch` method [here](https://github.com/ruby/ruby/blob/53ce3be2f0112ff67fdca0b4f527a3601a35bec4/hash.c#L913), and from the error it looks like Rubinius does not.

**Comment by brixen** [comment]
@eugenk looks like [this commit](https://github.com/libgit2/rugged/commit/bf087b0c667367a14e97dd1fc7a77a93bf41f272) changed `rb_hash_aref` to `rb_hash_fetch`, which is not yet implemented in Rubinius.

Rubinius implements MRI C-API functions when we are able to and when people use them. Since every C function in MRI is potentially usable in some C extension, there's really no other way to approach it.

Thanks for opening the Rubinius issue. We should be able to implement `rb_hash_fetch`.

This issue can be closed.
